<a href="https://colab.research.google.com/github/DepartmentOfStatisticsPUE/ann-for-survey-sampling/blob/main/ann_paper_simulation_2_data_integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!apt install libomp-dev
!pip install faiss-gpu
!pip install n2
!pip install scann
!pip install annoy ## takes minutes to add data and index
!pip install pyflann-py3
## !pip install pynndescent -- not suitable for PMM 1d dimension: gets error "no suitable hyperplains were found"

## this line cleanes information about installing
## comment these lines if you want to see the progress 
from IPython.display import clear_output 
clear_output()

In [3]:
## standard modules
import pandas as pd
import numpy as np
import time

## vis
import matplotlib.pyplot as plt

## linear regression
from sklearn.linear_model import LinearRegression

## ann modules
import scann
import faiss
from pyflann import *
from annoy import AnnoyIndex
from n2 import HnswIndex
from scipy.spatial import cKDTree
from pynndescent import NNDescent

## serialization
import pickle

In [4]:
def kdtree_impute_di(y_pred, y_pred_miss, y, eps = 0):
  tree = cKDTree(y_pred, leafsize = 100, balanced_tree=True)
  dists, indx = tree.query(y_pred_miss, k = 1, eps = eps)
  res = np.mean(y[indx])
  return res

def faiss_impute_di(y_pred, y_pred_miss, y, gpu = True, voronoi = False):
  index_flat = faiss.IndexFlatL2(2)

  if voronoi:
    index_flat = faiss.IndexIVFFlat(index_flat, 2, 1000)

  if gpu:
    gpu_faiss = faiss.StandardGpuResources() 
    index_flat = faiss.index_cpu_to_gpu(gpu_faiss, 0, index_flat)
  
  if voronoi:
    index_flat.train(y_pred)

  index_flat.add(y_pred)
  dists, indx = index_flat.search(y_pred_miss, k = 1) 
  res = np.mean(y[indx])
  return res

def annoy_impute_di(y_pred, y_pred_miss, y, trees = 50):
  t = AnnoyIndex(2, "euclidean") 
  for i in range(len(y_pred)):
    t.add_item(i, y_pred[i,:]) 

  t.build(trees)
  indx = np.array([t.get_nns_by_vector(i, 1) for i in y_pred_miss])
  res = np.mean(y[indx])
  return res

def n2_impute_di(y_pred, y_pred_miss, y, trees = 50):
  t = HnswIndex(2, "euclidean") 
  for i in y_pred:
    t.add_data(i)

  t.build(m=5, n_threads=-1)
  indx = t.batch_search_by_vectors(y_pred_miss, 1)
  res = np.mean(y[indx])
  return res

def flann_impute_di(y_pred, y_pred_miss, y, eps = 0):
  flann = FLANN()
  indx, dists = flann.nn(y_pred, y_pred_miss, 1, 
                       algorithm="kmeans", 
                       branching=32, iterations=7, checks=16, 
                       random_seed = 1, eps = eps)
  res = np.mean(y[indx])
  return res

def scann_impute_di(y_pred, y_pred_miss, y):
  searcher = scann.scann_ops_pybind.builder(y_pred, 1, "squared_l2").tree(
      num_leaves=1000, num_leaves_to_search=50, training_sample_size=5000).score_ah(
          2, anisotropic_quantization_threshold=0.2).reorder(10).build()
  indx, nns = searcher.search_batched(y_pred_miss)
  res = np.mean(y[indx])
  return res

Simulation study taken from: Kim, J. K., & Wang, Z. (2018). Sampling Techniques for Big Data Analysis. International Statistical Review, 1, 1–15. https://doi.org/10.1111/insr.12290

In [5]:
np.random.seed(123) 
N = 1000000
x1 = np.random.normal(loc=1.0,scale=1.0,size=N)
x2 = np.random.exponential(scale=1.0, size = N)
epsilon = np.random.normal(size=N)

### target variables
y1 = 1 + x1 + x2 + epsilon
y2 = 0.5*(x1 - 1.5)**2 + x2 + epsilon
## propensity scores
p1 = np.exp(x2) / (1 + np.exp(x2))
p2 = np.exp(-0.5 + 0.5*(x2-2)**2) / (1 + np.exp(-0.5 + 0.5*(x2-2)**2))

data = np.column_stack((x1,x2,y1,y2,p1,p2)).astype('float32')
data[:3]

array([[-0.0856306 ,  0.5546646 ,  0.90054107,  1.2432839 ,  0.63521713,
         0.632858  ],
       [ 1.9973454 ,  1.1975824 ,  4.455222  ,  1.5815529 ,  0.7680944 ,
         0.4556015 ],
       [ 1.2829785 ,  0.84342945,  3.0256119 ,  0.76618266,  0.699187  ,
         0.542107  ]], dtype=float32)

In [6]:
R = 500
xs = [0,1]
ys = [2,3]
ps = [4,5]

results_naive_500 = np.zeros(shape = (R, 3))
results_naive_1000 = np.zeros(shape = (R, 3))
results_faiss_500 = np.zeros(shape = (R, 3))
results_faiss_1000 = np.zeros(shape = (R, 3))
results_faiss_v_500 = np.zeros(shape = (R, 3))
results_faiss_v_1000 = np.zeros(shape = (R, 3))
results_kdtree_500 = np.zeros(shape = (R, 3))
results_kdtree_1000 = np.zeros(shape = (R, 3))
results_scann_500 = np.zeros(shape = (R, 3))
results_scann_1000 = np.zeros(shape = (R, 3))
results_flann_500 = np.zeros(shape = (R, 3))
results_flann_1000 = np.zeros(shape = (R, 3))

for r in range(R):
  print(r)
  np.random.seed(r)
  ## big data sample
  big_p1 = np.random.binomial(n=1, p = p1, size = N)
  big_p2 = np.random.binomial(n=1, p = p2, size = N)    
  ## random samples
  s500 = np.random.choice(a = data.shape[0], size = 500, replace = False)
  s1000 = np.random.choice(a = data.shape[0], size = 1000, replace = False)
  
  ## naive
  results_naive_500[r, 0] = np.mean(data[big_p1==1][:, ys[0]])
  results_naive_500[r, 1] = np.mean(data[big_p2==1][:, ys[0]])
  results_naive_500[r, 2] = np.mean(data[big_p1==1][:, ys[1]])
  results_naive_1000[r, 0] = np.mean(data[big_p1==1][:, ys[0]])
  results_naive_1000[r, 1] = np.mean(data[big_p2==1][:, ys[0]])
  results_naive_1000[r, 2] = np.mean(data[big_p1==1][:, ys[1]])

  ## imputation by kdtree
  results_kdtree_500[r,0]=kdtree_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[0]])
  results_kdtree_500[r,1]=kdtree_impute_di(data[big_p2==1][:, xs], data[s500][:, xs], data[big_p2==1][:, ys[0]])
  results_kdtree_500[r,2]=kdtree_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[1]])
  results_kdtree_1000[r,0]=kdtree_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[0]])
  results_kdtree_1000[r,1]=kdtree_impute_di(data[big_p2==1][:, xs], data[s1000][:, xs], data[big_p2==1][:, ys[0]])
  results_kdtree_1000[r,2]=kdtree_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[1]])
  
  ## imputation by faiss
  results_faiss_500[r,0]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p1==1][:, ys[0]].copy())
  results_faiss_500[r,1]=faiss_impute_di(data[big_p2==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p2==1][:, ys[0]].copy())
  results_faiss_500[r,2]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p1==1][:, ys[1]].copy())
  results_faiss_1000[r,0]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p1==1][:, ys[0]].copy())
  results_faiss_1000[r,1]=faiss_impute_di(data[big_p2==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p2==1][:, ys[0]].copy())
  results_faiss_1000[r,2]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p1==1][:, ys[1]].copy())
  
  ## imputation by faiss with voronoi
  results_faiss_v_500[r,0]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p1==1][:, ys[0]].copy(), voronoi=True)
  results_faiss_v_500[r,1]=faiss_impute_di(data[big_p2==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p2==1][:, ys[0]].copy(), voronoi=True)
  results_faiss_v_500[r,2]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s500][:, xs].copy(), data[big_p1==1][:, ys[1]].copy(), voronoi=True)
  results_faiss_v_1000[r,0]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p1==1][:, ys[0]].copy(), voronoi=True)
  results_faiss_v_1000[r,1]=faiss_impute_di(data[big_p2==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p2==1][:, ys[0]].copy(), voronoi=True)
  results_faiss_v_1000[r,2]=faiss_impute_di(data[big_p1==1][:, xs].copy(), data[s1000][:, xs].copy(), data[big_p1==1][:, ys[1]].copy(), voronoi=True)

  ## imputation by scann
  results_scann_500[r,0]=scann_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[0]])
  results_scann_500[r,1]=scann_impute_di(data[big_p2==1][:, xs], data[s500][:, xs], data[big_p2==1][:, ys[0]])
  results_scann_500[r,2]=scann_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[1]])
  results_scann_1000[r,0]=scann_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[0]])
  results_scann_1000[r,1]=scann_impute_di(data[big_p2==1][:, xs], data[s1000][:, xs], data[big_p2==1][:, ys[0]])
  results_scann_1000[r,2]=scann_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[1]])

  ## imputation by flann
  results_flann_500[r,0]=flann_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[0]])
  results_flann_500[r,1]=flann_impute_di(data[big_p2==1][:, xs], data[s500][:, xs], data[big_p2==1][:, ys[0]])
  results_flann_500[r,2]=flann_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[1]])
  results_flann_1000[r,0]=flann_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[0]])
  results_flann_1000[r,1]=flann_impute_di(data[big_p2==1][:, xs], data[s1000][:, xs], data[big_p2==1][:, ys[0]])
  results_flann_1000[r,2]=flann_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[1]])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [8]:
y_trues = [np.mean(y1), np.mean(y1), np.mean(y2)]

mse_500 = [
 np.std(results_naive_500, axis = 0)**2 + (np.mean(results_naive_500, axis = 0) - y_trues)**2,
 np.std(results_kdtree_500, axis = 0)**2 + (np.mean(results_kdtree_500, axis = 0) - y_trues)**2,
 np.std(results_faiss_500, axis = 0)**2 + (np.mean(results_faiss_500, axis = 0) - y_trues)**2,
 np.std(results_faiss_v_500, axis = 0)**2 + (np.mean(results_faiss_v_500, axis = 0) - y_trues)**2,
 np.std(results_flann_500, axis = 0)**2 + (np.mean(results_flann_500, axis = 0) - y_trues)**2,
 np.std(results_scann_500, axis = 0)**2 + (np.mean(results_scann_500, axis = 0) - y_trues)**2
 ]

np.sqrt(mse_500)


array([[0.18629595, 0.09812589, 0.1863322 ],
       [0.0728451 , 0.0725048 , 0.07351158],
       [0.07305342, 0.07315092, 0.07323317],
       [0.07294611, 0.07232721, 0.07355501],
       [0.07260879, 0.07246655, 0.07341788],
       [0.09485428, 0.10635519, 0.11017833]])

In [9]:
mse_1000 = [
np.std(results_naive_1000, axis = 0)**2 + (np.mean(results_naive_1000, axis = 0) - y_trues)**2,
 np.std(results_kdtree_1000, axis = 0)**2 + (np.mean(results_kdtree_1000, axis = 0) - y_trues)**2,
 np.std(results_faiss_1000, axis = 0)**2 + (np.mean(results_faiss_1000, axis = 0) - y_trues)**2,
 np.std(results_faiss_v_1000, axis = 0)**2 + (np.mean(results_faiss_v_1000, axis = 0) - y_trues)**2,
 np.std(results_flann_1000, axis = 0)**2 + (np.mean(results_flann_1000, axis = 0) - y_trues)**2,
 np.std(results_scann_1000, axis = 0)**2 + (np.mean(results_scann_1000, axis = 0) - y_trues)**2
 ]
np.sqrt(mse_1000)

array([[0.18629595, 0.09812589, 0.1863322 ],
       [0.05212807, 0.05165673, 0.04802686],
       [0.05202064, 0.05180245, 0.04750207],
       [0.05231552, 0.05124359, 0.04791906],
       [0.05249797, 0.05160239, 0.04823994],
       [0.07995406, 0.08813845, 0.09225194]])

In [10]:
results = {
    "data": pd.DataFrame(data),
    "results_naive_500" : pd.DataFrame(results_naive_500),
    "results_naive_1000" : pd.DataFrame(results_naive_1000),
    "results_faiss_500" : pd.DataFrame(results_faiss_500),
    "results_faiss_1000" : pd.DataFrame(results_faiss_1000),
    "results_faiss_v_500" : pd.DataFrame(results_faiss_v_500),
    "results_faiss_v_1000" : pd.DataFrame(results_faiss_v_1000),
    "results_kdtree_500" : pd.DataFrame(results_kdtree_500),
    "results_kdtree_1000" : pd.DataFrame(results_kdtree_1000),
    "results_scann_500" : pd.DataFrame(results_scann_500),
    "results_scann_1000" : pd.DataFrame(results_scann_1000),
    "results_flann_500" : pd.DataFrame(results_flann_500),
    "results_flann_1000" : pd.DataFrame(results_flann_1000),
          }

f = open("sim2-results.pkl","wb")
pickle.dump(results,f)
f.close()

# Approximate nearest neighbours using K-D Tree

In [22]:
R = 500
xs = [0,1]
ys = [2,3]
ps = [4,5]


sim_ann_kdtree_500_p1 = np.zeros(shape = (R, 6))
sim_ann_kdtree_1000_p1 = np.zeros(shape = (R, 6))
sim_ann_kdtree_500_p2 = np.zeros(shape = (R, 6))
sim_ann_kdtree_1000_p2 = np.zeros(shape = (R, 6))
sim_ann_kdtree_500_p3 = np.zeros(shape = (R, 6))
sim_ann_kdtree_1000_p3 = np.zeros(shape = (R, 6))
sim_ann_naive = np.zeros(shape = (R, 3)) 

for r in range(R):
  print(r)
  np.random.seed(r)
  ## big data sample
  big_p1 = np.random.binomial(n=1, p = p1, size = N)
  big_p2 = np.random.binomial(n=1, p = p2, size = N)    
  ## random samples
  s500 = np.random.choice(a = data.shape[0], size = 500, replace = False)
  s1000 = np.random.choice(a = data.shape[0], size = 1000, replace = False)
  
  sim_ann_naive[r, :]=np.array([np.mean(data[big_p1==1][:, ys[0]]), np.mean(data[big_p2==1][:, ys[0]]), np.mean(data[big_p1==1][:, ys[1]])])
  sim_ann_kdtree_500_p1[r,:]=np.array([kdtree_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[0]], eps = i) for i in [0, 1, 5, 10, 50, 100]])
  sim_ann_kdtree_500_p2[r,:]=np.array([kdtree_impute_di(data[big_p2==1][:, xs], data[s500][:, xs], data[big_p2==1][:, ys[0]], eps = i) for i in [0, 1, 5, 10, 50, 100]])
  sim_ann_kdtree_500_p3[r,:]=np.array([kdtree_impute_di(data[big_p1==1][:, xs], data[s500][:, xs], data[big_p1==1][:, ys[1]], eps = i) for i in [0, 1, 5, 10, 50, 100]])
  sim_ann_kdtree_1000_p1[r,:]=np.array([kdtree_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[0]], eps = i) for i in [0, 1, 5, 10, 50, 100]])
  sim_ann_kdtree_1000_p2[r,:]=np.array([kdtree_impute_di(data[big_p2==1][:, xs], data[s1000][:, xs], data[big_p2==1][:, ys[0]], eps = i) for i in [0, 1, 5, 10, 50, 100]])
  sim_ann_kdtree_1000_p3[r,:]=np.array([kdtree_impute_di(data[big_p1==1][:, xs], data[s1000][:, xs], data[big_p1==1][:, ys[1]], eps = i) for i in [0, 1, 5, 10, 50, 100]])



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [23]:
[(np.mean(sim_ann_kdtree_500_p3, axis = 0) - np.mean(data[:, ys[1]]))/np.mean(data[:, ys[1]])*100,
 (np.mean(sim_ann_kdtree_1000_p3, axis = 0) - np.mean(data[:, ys[1]]))/np.mean(data[:, ys[1]])*100]

[array([-0.17556401, -0.16701453, -0.15504449, -0.1649777 , -0.15760982,
        -0.15825315]),
 array([0.05063885, 0.04206349, 0.04992578, 0.04209391, 0.03819169,
        0.03205324])]

In [25]:
results = {
    "data": pd.DataFrame(data),
"sim_ann_kdtree_500_p1" : pd.DataFrame(sim_ann_kdtree_500_p1),
"sim_ann_kdtree_1000_p1" : pd.DataFrame(sim_ann_kdtree_1000_p1),
"sim_ann_kdtree_500_p2" : pd.DataFrame(sim_ann_kdtree_500_p2),
"sim_ann_kdtree_1000_p2" : pd.DataFrame(sim_ann_kdtree_1000_p2),
"sim_ann_kdtree_500_p3" : pd.DataFrame(sim_ann_kdtree_500_p3),
"sim_ann_kdtree_1000_p3" : pd.DataFrame(sim_ann_kdtree_1000_p3),
"sim_ann_naive" : pd.DataFrame(sim_ann_naive)
      }

f = open("sim2-ann-kdtree-results.pkl","wb")
pickle.dump(results,f)
f.close()