<a href="https://colab.research.google.com/github/DepartmentOfStatisticsPUE/ann-for-survey-sampling/blob/main/notebooks/ann_paper_sim_study_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider SPTAG (https://github.com/microsoft/SPTAG/blob/master/docs/examples/QuickstartGuide.ipynb)

In [14]:
#!pip install -q condacolab
#import condacolab
#condacolab.install()
#!conda install -c conda-forge cupy cudatoolkit=10.0
!apt install libomp-dev
!pip install faiss-gpu
!pip install n2
!pip install scann
!pip install annoy
!pip install pyflann-py3

⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:36
🔁 Restarting kernel...


In [46]:
import pandas as pd
import numpy as np
## https://docs.cupy.dev/en/stable/tutorial/basic.html 
## https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-conda-forge
#import cupy as cp 
#import cupyx as cpx
import statsmodels.api as sm ## is this needed?
import pickle
import time

import scann
import faiss
from pyflann import *
from annoy import AnnoyIndex
from n2 import HnswIndex
from scipy.spatial import KDTree
from scipy.spatial.distance import euclidean
from sklearn.neighbors import NearestNeighbors

res = faiss.StandardGpuResources() 

In [254]:
def kdtree_impute(tree, sample, data, y, x, eps = 0):
  nns = tree.query(sample[:,x], k = 1, eps = eps)
  res = np.mean(data[nns[1]][:, ys], axis = 0)
  return res

## Simulation 3A

Simulation study taken from: Kim, J. K., & Wang, Z. (2018). Sampling Techniques for Big Data Analysis. International Statistical Review, 1, 1–15. https://doi.org/10.1111/insr.12290

In [252]:
#t = time.time()
np.random.seed(123) 
N = 1000000
x1 = np.random.normal(loc=1.0,scale=1.0,size=N)
x2 = np.random.exponential(scale=1.0, size = N)
epsilon = np.random.normal(size=N)

### target variables
y1 = 1 + x1 + x2 + epsilon
y2 = 0.5*(x1 - 1.5)**2 + x2 + epsilon
## propensity scores
p1 = np.exp(x2) / (1 + np.exp(x2))
p2 = np.exp(-0.5 + 0.5*(x2-2)**2) / (1 + np.exp(-0.5 + 0.5*(x2-2)**2))

data = np.column_stack((x1,x2,y1,y2,p1,p2)).astype('float32')
#time.time() - t
data[:3]

array([[-0.0856306 ,  0.5546646 ,  0.90054107,  1.2432839 ,  0.63521713,
         0.632858  ],
       [ 1.9973454 ,  1.1975824 ,  4.455222  ,  1.5815529 ,  0.7680944 ,
         0.4556015 ],
       [ 1.2829785 ,  0.84342945,  3.0256119 ,  0.76618266,  0.699187  ,
         0.542107  ]], dtype=float32)

In [269]:
R = 10
xs = [0,1]
ys = [2,3]
ps = [4,5]

results_faiss_500 = np.zeros(shape = (R, 2))
results_faiss_1000 = np.zeros(shape = (R, 2))
results_kdtree_500 = np.zeros(shape = (R, 2))
results_kdtree_1000 = np.zeros(shape = (R, 2))

for r in range(R):
  print(r)
  np.random.seed(r)
  ## big data sample
  big_p1 = np.random.binomial(n=1, p = p1, size = N)
  big_p2 = np.random.binomial(n=1, p = p2, size = N)    
  ## random samples
  s500 = np.random.choice(a = data.shape[0], size = 500, replace = False)
  s1000 = np.random.choice(a = data.shape[0], size = 1000, replace = False)
  ## kdtree (exact)
  kdtree = KDTree(data[big_p2==1][:, xs], leafsize = 100)
  results_kdtree_500[r, :] = kdtree_impute(kdtree, data[s500], data[big_p2==1], ys, xs, eps = 0)
  results_kdtree_1000[r, :] = kdtree_impute(kdtree, data[s1000], data[big_p2==1], ys, xs, eps = 0)
  ## faiss
  big_data = data[big_p2==1][:, xs].copy()
  sam_data_500 = data[s500][:, xs].copy()
  sam_data_1000 = data[s1000][:, xs].copy()
  index_flat = faiss.IndexFlatL2(len(xs))
  gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index_flat)
  gpu_index_flat.add(big_data)
  D_500, I_500 = gpu_index_flat.search(sam_data_500, k = 1) 
  D_1000, I_1000 = gpu_index_flat.search(sam_data_1000, k = 1) 
  results_faiss_500[r,:]=np.mean(data[big_p2==1][I_500.flatten()][:, ys], axis=0)
  results_faiss_1000[r,:]=np.mean(data[big_p2==1][I_1000.flatten()][:, ys], axis=0)

0
1
2
3
4
5
6
7
8
9


In [270]:
expected = np.stack(
    [np.mean(results_kdtree_500, axis=0),
     np.mean(results_faiss_500, axis=0),
     np.mean(results_kdtree_1000, axis=0),
     np.mean(results_faiss_1000, axis=0)
     ]
) 

stderrs =  np.stack(
    [np.std(results_kdtree_500, axis=0),
     np.std(results_faiss_500, axis=0),
     np.std(results_kdtree_1000, axis=0),
     np.std(results_faiss_1000, axis=0)
     ]
)

bias = expected - np.mean(data[:,ys], axis=0)
mse = bias**2 + stderrs**2

print("===== bias =====")
print(bias)
print("===== se =====")
print(stderrs)
print("===== mse =====")
print(mse)

===== bias =====
[[-0.0095598  -0.03190564]
 [-0.0071245  -0.02946934]
 [ 0.03106031  0.01321316]
 [ 0.03051281  0.01266494]]
===== se =====
[[0.0561105  0.10153849]
 [0.05479202 0.09999034]
 [0.05094645 0.04202207]
 [0.05184517 0.04317867]]
===== mse =====
[[0.00323978 0.01132803]
 [0.00305292 0.01086651]
 [0.00356028 0.00194044]
 [0.00361895 0.0020248 ]]


In [ ]:
## save results
results = {
    "results_kdtree_500" : pd.DataFrame(results_kdtree_500),
    "results_faiss_500" : pd.DataFrame(results_faiss_500),
    "results_kdtree_1000": pd.DataFrame(results_kdtree_1000),
    "results_faiss_1000": pd.DataFrame(results_faiss_1000),
           }

f = open("kdtree_faiss_500_1000k.pkl","wb")
pickle.dump(results,f)
f.close()

## Simulation 3B

Modified case from: Yang, S., & Kim, J. K. (2019). Nearest neighbour imputation for general parameter estimation in survey sampling. In The Econometrics of Complex Survey Data: Theory and Applications (Vol. 39, pp. 209–234)

In [4]:
def kdtree_impute2(tree, data_obs, data_not, y, x, N, eps = 0):
  nns = tree.query(data_not[:,xs], k = 1, eps = eps)
  res = (np.sum(data_obs[nns[1]][:, ys], axis = 0) + np.sum(data_obs[:, ys], axis = 0)) / N
  return res

In [3]:
np.random.seed(123)
N = 500000
x1 = np.random.uniform(size = N)
x2 = np.random.uniform(size = N)
x3 = np.random.uniform(size = N)
x4 = np.random.normal(size = N)
x5 = np.random.normal(size = N)
x6 = np.random.normal(size = N)
epsilon = np.random.normal(size=N)

### target variables
y1 = -1 + x1 + x2 + epsilon
y2 = -1.5 + x1 + x2 + x3 + x4 + epsilon
y3 = -1.5 + x1 + x2 + x3 + x4 + x5 + x6 + epsilon
y4 = -1 + x1 + x2 + x1**2 + x2**2 -2/3 + epsilon
y5 = -1 + x1 + x2 + x3 + x4 + x1**2 + x2**2 -2/3 + epsilon
y6 = -1 + x1 + x2 + x3 + x4 + x5 + x6 + x1**2 + x2**2 -2/3 + epsilon

## propensity scores
p1 = np.exp(1 + x1 + x2 + x3 + x4 + x5 + x6) / (1 + np.exp(1 + x1 + x2 + x3 + x4 + x5 + x6))
p2 = np.exp(1 + x1 + x2) / (1 + np.exp(1 + x1 + x2))

data = np.column_stack((x1,x2,x3,x4,x5,x6,y1,y2,y3,y4,y5,y6)).astype('float32')
data[:3]

array([[ 0.6964692 ,  0.39244577,  0.772698  ,  0.06619908,  1.181968  ,
         0.33423862,  0.454862  ,  0.79375905,  2.3099656 ,  0.42727834,
         1.2661754 ,  2.782382  ],
       [ 0.28613934,  0.46933195,  0.46711504,  0.33278647,  0.22954535,
         0.11521499,  0.9884662 ,  1.2883677 ,  1.633128  ,  0.62394774,
         1.4238492 ,  1.7686096 ],
       [ 0.22685145,  0.62351155,  0.01994883, -1.044568  ,  0.11454313,
        -0.31842756, -2.2750313 , -3.7996504 , -4.003535  , -2.5014696 ,
        -3.5260887 , -3.7299733 ]], dtype=float32)

In [5]:
R = 1
xs = [0,1,2,3,4,5]
ys = [6,7,8,9,10,11]

results_faiss = np.zeros(shape = (R, 6))
results_kdtree = np.zeros(shape = (R, 6))
results_pmm = np.zeros(shape = (R, 6))
results_identical = np.zeros(shape = (R,1))
timing_faiss = 0
timing_kdtree = 0

for r in range(R):
  print(r)
  np.random.seed(r)
  ## big data sample
  big_p1 = np.random.binomial(n=1, p = p1, size = N)
  ## data
  data_obs = data[big_p1 == 1]
  data_not = data[big_p1 != 1]
  ## running
  X_obs = data_obs[:, xs]
  X_obs = sm.add_constant(X_obs)
  y_obs = data_obs[:, ys[5]]
  ols_y = sm.OLS(y_obs, X_obs).fit()
  X_not = data_not[:, xs]
  X_not = sm.add_constant(X_not)
  y_not = np.dot(X_not, ols_y.params)
  
  ## nearest nn
  t = time.time()
  neigh = NearestNeighbors(n_neighbors=1, algorithm='kd_tree').fit(ols_y.fittedvalues.reshape(-1, 1))
  dists, inds = neigh.kneighbors(y_not.reshape(-1,1), return_distance=True)
  timing_kdtree += time.time() - t
  results_pmm[r, 5] = (np.sum(y_obs) + np.sum(y_obs[inds]))/N

  #neigh = NearestNeighbors(n_neighbors=5, algorithm='kd_tree').fit(ols_y.fittedvalues.reshape(-1, 1))
  #inds = neigh.kneighbors(y_not.reshape(-1,1), return_distance=False)
  #results_pmm[r, 5] = (np.sum(y_obs) + np.sum(np.mean(y_obs[inds], axis=1))) /N
  ## faiss
  data_obs_faiss = ols_y.fittedvalues.copy().reshape(-1, 1).astype('float32')
  data_not_faiss = y_not.copy().reshape(-1, 1).astype('float32')
  
  t = time.time()
  index_flat = faiss.IndexFlatL2(1)
  index_flat = faiss.IndexIVFFlat(index_flat, 1, 1000) ## number of cells = 1000
  gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index_flat)
  gpu_index_flat.train(data_obs_faiss)
  gpu_index_flat.add(data_obs_faiss)
  faiss_dists, faiss_inds = gpu_index_flat.search(data_not_faiss, k = 1)
  timing_faiss += time.time() - t

  results_faiss[r, 5] = (np.sum(y_obs) + np.sum(y_obs[faiss_inds]))/N
  #faiss_dists, faiss_inds = gpu_index_flat.search(data_not_faiss, k = 5) 
  #results_faiss[r, 5] =  (np.sum(y_obs) + np.sum(np.mean(y_obs[faiss_inds], axis = 1)))/N
  ## identical
  results_identical[r, 0] = sum(inds.flatten() == faiss_inds.flatten()) / len(data_not_faiss)
  ## kdtree
  #kdtree = KDTree(data_obs_faiss, leafsize = 10)
  #dd, ii = kdtree.query(data_not_faiss, k=1)
  #results_kdtree[r,:]= (np.sum(data_obs[ii][:, ys], axis=0) + np.sum(data_obs[:, ys], axis=0)) / N

0


In [249]:
timing_faiss, timing_kdtree

(31.84601902961731, 143.03165912628174)

In [250]:
np.mean(results_identical)

0.9964409603961438

In [246]:
expected = np.stack(
    [np.mean(results_kdtree, axis=0),
     np.mean(results_faiss, axis=0)
     ]
) 

stderrs =  np.stack(
    [np.std(results_kdtree, axis=0),
     np.std(results_faiss, axis=0)
     ]
)

bias = expected - np.mean(data[:,ys], axis=0)
mse = bias**2 + stderrs**2

print("===== bias =====")
print(bias[:,5])
print("===== se =====")
print(stderrs[:, 5])
print("===== mse =====")
print(np.round(mse,4))
print(np.round(expected,4))
print("===== pmm =====")
print(np.mean(results_pmm[:, 5])-np.mean(data[:,ys[5]], axis=0))
print(np.std(results_pmm[:, 5]))

===== bias =====
[-0.49780464  0.00197833]
===== se =====
[0.         0.00267703]
===== mse =====
[[0.     0.     0.     0.     0.2499 0.2478]
 [0.     0.     0.     0.     0.2499 0.    ]]
[[0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.4998]]
===== pmm =====
0.002013671557617114
0.0026393419641810977


In [193]:
t = time.time()
print(np.mean(dists))
print(np.mean(faiss_dists))

compare_dists = pd.DataFrame(data = np.column_stack((dists.flatten(), faiss_dists.flatten())),
                             columns = ["kdtree","faiss"])
compare_dists.corr(method = "pearson")
#compare_dists.plot.scatter(x = "kdtree", y = "faiss")
timing_faiss =0
timing_faiss += 1
timing_faiss

0.0029696094117184473
0.0011865322


1

## Simulation 3C

Study from Yang, S., & Kim, J. K. (2020). Doubly robust inference when combining probability and non-probability samples with high dimensional. Journal of the Royal Statistical Society. Series B: Statistical Methodology, 82(2), 445–465. https://doi.org/10.1111/rssb.12354

R code (source: https://github.com/shuyang1987/IntegrativeFPM)

```r
set.seed(1234)
## population size
N <- 10000
## x is a p-dimensional covariate
p <- 50
x <- matrix( rnorm(N*p,0,1),N,p)
## y is a continuous outcome 
beta0 <- c(1,1,1,1,1,rep(0,p-4))
y <- cbind(1,x)%*%beta0 + rnorm(N,0,1)
true <- mean(y)
## y2 is a binary outcome
ly2 <- (cbind(1,x)%*%beta0)
ply <- exp(ly2)/(1+exp(ly2))
y2 <- rbinom(N,1,ply)
true2 <- mean(y2)
## A.set is a prob sample: SRS
## sampling probability into A is known when estimation
nAexp <- 1000
probA <- rep(nAexp/N,N)
A.index <- rbinom(N,size = 1,prob = probA)
A.loc <- which(A.index == 1)
nA <- sum(A.index == 1)
sw.A <- 1/probA[A.loc]
x.A <- x[A.loc,]
y.A <- rep(NA,nA) # y is not observed in Sample A
y2.A <- rep(NA,nA)
## B.set is a nonprob sample
## sampling probability into B is unknown when estimation
nBexp <- 2000
alpha0 <- c(-2,1,1,1,1,rep(0,p-4))
probB <- (1+exp(-cbind(1,x)%*%alpha0))^(-1) 
B.index <- rbinom(N,size = 1,prob = probB)
B.loc <- which(B.index == 1)
nB <- sum(B.index)
x.B <- x[B.loc,]
y.B <- y[B.loc]
y2.B <- y2[B.loc]
## combined dataset
y.AB <- c(y.A,y.B)
y2.AB <- c(y2.A,y2.B)
x.AB <- rbind(x.A,x.B)
deltaB <- c(rep(0,nA),rep(1,nB))
sw <- c(sw.A,rep(1,nB))
```

playground

In [6]:
f = 1
t = HnswIndex(f, "L2")  # HnswIndex(f, "angular, L2, or dot")
for i in ols_y.fittedvalues.reshape(-1,1):
    t.add_data(i)
t.build(m=5, max_m0=10, n_threads=4)

[[0], [1], [3]]

In [11]:
y_res = t.batch_search_by_vectors(y_not.reshape(-1,1), 1)

(np.sum(y_obs) + np.sum(y_obs[y_res]))/N

0.5016740625

In [52]:
f = 1
t = AnnoyIndex(f, "euclidean")  # HnswIndex(f, "angular, L2, or dot")
for i in range(1000):
  t.add_item(i, ols_y.fittedvalues.reshape(-1,1)[i])

t.build(50)

True

In [53]:
annoy_inds = np.array([t.get_nns_by_vector(i, 1) for i in y_not.reshape(-1,1)])
(np.sum(y_obs) + np.sum(y_obs[annoy_inds]))/N

0.5154144375

In [57]:
flann = FLANN()
result, dists = flann.nn(
    ols_y.fittedvalues.reshape(-1,1), 
    y_not.reshape(-1,1), 1, 
    algorithm="kmeans", branching=32, iterations=7, checks=16)

(np.sum(y_obs) + np.sum(y_obs[result]))/N

0.5018105